### ISSUE TITLE
Original install image

### ISSUE THREAD

**Issue by xadacka** [AlphamaxMedia/netv2-fpga#35]
Hey!

So I've had this running for years without many issues, but I've recently wanted to add new features to what I use it for and wanted to start fresh so installed a clean copy of Raspbian Lite.

Unfortunately, I'm unable to get the tools running as the files required and listed in the readme go to dead links and the required software seems to be unavailable any more. 

Can you please provide the image for the original included SD card? Or, if possible, provide a script and the required files to get an empty install set-up?

**Comment by bunnie** [comment]
The disk image should be at:

https://bunniefoo.com/netv2/netv2-production-image.img.gz

You can prepare this if you have a Linux machine by running

`zcat netv2-production-image.img.gz | sudo dd of=/dev/sdX bs=1M # replace sdX with the node of your SD card`

The dead links you're referring to -- are these the SiFive toolchain, etc?

**Comment by xadacka** [comment]
Thank you for the swift reply! 

Yes, the SiFive toolchain doesn't seem to be available at all. It's listed on [this](https://www.sifive.com/software) page, but when I signed up the link directs to a core designer with no sign of any downloads anywhere there.

**Comment by bunnie** [comment]
Yah, I'll fix that. The SiFive toolchain got sucky, in part because they require sign-ups and it's impossible to find the software.

**Comment by xadacka** [comment]
I was going to submit a PR with updated links if I was able to figure it out but sadly that didn't pan out.

Thanks for the image though, downloaded and flashed and working perfectly.
