### ISSUE TITLE
Git Clone Fails Due to missing submodule

### ISSUE THREAD

**Issue by jcreedon** [AlphamaxMedia/netv2-fpga#6]
Cloning the repo failed while recusing into `deps/litex`. In [litex ](https://github.com/AlphamaxMedia/litex) it appears that `litex/build/sim/core/modules/ethernet/tapcfg` points to https://github.com/nizox/tapcfg/ which no longer exists.

Looks like in upstream litex this got moved to https://github.com/enjoy-digital/tapcfg

I've updated this locally and I think it is working just fine. Not sure how you want it corrected in the repo because it looks like you are pinning a particular version.

**Comment by bunnie** [comment]
Thanks, hopefully I've fixed it with this commit:

https://github.com/AlphamaxMedia/litex/commit/c692e62b1cf0d30ea2a3f62ddc342423fa481f0e
