### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by tommythorn** [AlphamaxMedia/netv2-fpga#9]
The docs states "The latest hardware docs are maintained in a separate git repository." but doesn't name any or point anywhere. It's doesn't look like any of the AlphamaxMedia repos are the documentation for this.

**Comment by bunnie** [comment]
Can you point me to where you're seeing this? If you go to 

https://github.com/AlphamaxMedia/netv2-fpga/wiki

You'll find that "PCB, plastics, production testing software" are each hyperlinks to three separate repositories for the PCB, plastics, and production testing software respectively.

**Comment by tommythorn** [comment]
https://github.com/AlphamaxMedia/netv2-fpga/tree/master/doc

**Comment by bunnie** [comment]
OK, that's an out of date stub and I've deleted it. Please refer to the README file for the pointer to the wiki which contains the links I mentioned above to all the hardware docs.
